name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./dorcbot/requirements.txt
    - name: Run Tests
      run: |
        python -m unittest
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.ag7su.com/tcarwash/dorcbot:$(date +%s)
